services:
  - type: web
    name: litoral-blaze-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: DB_DIR
        value: /var/data
    disk:
      name: litoral-db
      mountPath: /var/data
      sizeGB: 1
